### ISSUE TITLE
Lineas de código comentadas

### ISSUE THREAD

**Issue by FelipeVelasquez1717** [semillasbabel/WikiHarryPotter-StarWars#11]
Se encuentra lineas de código comentadas, se solicita la revisión de estas y la eliminación en caso tal de no ser necesarias.

**Comment by FelipeVelasquez1717** [comment]
Se encuentra que en el archivo HousesComponent.js hay lineas comentadas en la linea 54

**Comment by FelipeVelasquez1717** [comment]
Se encuentra lineas comentadas en el archivo llamado Detailsmovie.js

**Comment by FelipeVelasquez1717** [comment]
Se encuentra MUCHO código comentado en el arcvhivo MenuSW.js, revisar si es algo util de lo contrario eliminarlo.

**Comment by FelipeVelasquez1717** [comment]
Revisar todo el proyecto y verificar que no se encuentre más código comentado.

**Comment by Hugoch13** [comment]
codigo comentado eliminado
